name: Zephyr Release

on:
  push:
    branches:
      - main 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  zephyr-release:
    runs-on: ubuntu-latest

    steps:

      - name: Run Zephyr Release
        uses: Pandoriux/zephyr-release@canary
        with:
          config-path: ".zephyr-release/config.jsonc"
          config-format: "jsonc"